name: matthew-abraham-law
favicon: null
layout_spectrum: 0.48810713295824826
typography_spectrum: 0.2390682348050177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.46939727920107543
  lightness: 0.24601168441586196
  saturation: 0.3290360749233514
  rhythmicContrast: 0.34732093615457416
purpose: []
